name: Test2 (For Ubuntu)

on: workflow_dispatch

permissions:
  actions: write
  security-events: write

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build Environments
      run: |
        sudo apt update
        sudo apt install git cmake build-essential nasm ninja-build gh
        sudo apt install ffmpeg p7zip
        
        export HOME=${{ github.workspace }}
        BUILD_LIBS=${HOME}/build_libs
        export PATH=${BUILD_LIBS}/bin:${PATH}
        export PKG_CONFIG_PATH=${BUILD_LIBS}/lib/pkgconfig:${PKG_CONFIG_PATH}
        git clone https://github.com/kskshaf/x265-mod.git
        cd x265-mod
        mkdir build/10b
        cd build/10b
        sudo cmake -GNinja ../../source -DHIGH_BIT_DEPTH=ON -DENABLE_SHARED=OFF -DUSE_MIMALLOC=OFF -DUSE_LTO=ON -DTARGET_CPU=native -DCMAKE_ASM_NASM_FLAGS=-w-macro-params-legacy
        sudo ninja
        sudo ninja install

        curl -s -o 11.7z -L https://github.com/fu-loser-ck/MyPacks/releases/download/vsenv/11.7z
        7z x 11.7z
        
        rm -rf 11.7z

    - name: Run
      shell: bash
      run: |
        set -ex
        ffmpeg -v 0 -i ./11.mkv -f yuv4mpegpipe -strict -1 - | x265 --input - --y4m -D 10 --preset slower --ctu 32 --crf 18.0 --qg-size 32 --tu-inter-depth 1 --tu-intra-depth 1 --max-tu-size 32 --deblock -1:-1 --pbratio 1.2 --cbqpoffs -2 --crqpoffs -2 --no-sao --me 3 --subme 5 --merange 57 --limit-tu 0 --b-intra --no-rect --no-amp --ref 5 --weightb --keyint 240 --min-keyint 1 --bframes 6 --aq-mode 3 --aq-strength 0.80 --rd 5 --psy-rd 1.6 --psy-rdoq 0.9 --vbv-maxrate 30000 --vbv-bufsize 36000 --rdoq-level 2 --no-open-gop --rc-lookahead 80 --scenecut 40 --qcomp 0.65 --no-strong-intra-smoothing --colorprim bt709 --transfer bt709 --colormatrix bt709 --pools + -o ./11.hevc

    - name: Compress artifact
      run: |
        7z a -t7z -mx=7 enc-result.7z 11.hevc
        mkdir result
        cp enc-result.7z result/enc-result.7z

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: encode-result
        path: result/*

    - name: Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
      with:
        tag_name: encode-result
        files: enc-result.7z
        fail_on_unmatched_files: true
        generate_release_notes: false
        prerelease: true
