name: Test-x264 (Windows)

on: workflow_dispatch

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Download & Unpack Environments
      run: |
        curl -s -o vs.7z -L https://github.com/fu-loser-ck/MyPacks/releases/download/vsenv/VapourSynthR61.7z
        7z x vs.7z

        curl -s -o x264.7z -L https://github.com/jpsdr/x264/releases/download/r3107.1/x264_tmod_r3107.1.7z
        7z x x264.7z
        move .\posix\x264_64.exe .\

        curl -s -o 11.7z -L https://github.com/fu-loser-ck/MyPacks/releases/download/vsenv/11.7z
        7z x 11.7z
         
        del /q /s vs.7z
        del /q /s x264.7z
        del /q /s 11.7z

    - name: Run vspipe
      shell: bash
      run: |
        set -ex
        echo -e "import vapoursynth as vs\nvs.core.ffms2.Source(\"11.mkv\").set_output()" > bangdream-action.vpy
        VapourSynthR61/vspipe -c y4m bangdream-action.vpy - | ./x264_64 -demuxer y4m --preset veryslow --profile high --crf 19.0 --deblock -1:-1 --keyint 480 --min-keyint 1 --ref 9 --vbv-bufsize 30000 --vbv-maxrate 25000 --chroma-qp-offset 1 --qcomp 0.65 --rc-lookahead 80 --aq-mode 3 --aq-strength 0.80 --merange 24 --fgo 1 --psy-rd 0.40:0.15 --no-fast-pskip --colorprim bt709 --transfer bt709 --colormatrix bt709 --subme 10 -o 11.264 -

    - name: Compress artifact
      run: |
        7z a -t7z -mx=7 enc-result.7z 11.264
        mkdir result
        cop=y enc-result.7z result/enc-result.7z

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: encode-result
        path: result/*

    - name: Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
      with:
        tag_name: encode-result
        files: enc-result.7z
        fail_on_unmatched_files: true
        generate_release_notes: false
        prerelease: true
